# Exercício 1 - Pandas

## Importação

In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("../datasets/classification_results_trial_0001.csv")

In [6]:
df

       image_path real_class predicted_class  prob_benign  prob_malign
0   image_001.jpg     malign          malign     0.031429     0.968571
1   image_002.jpg     benign          benign     0.636410     0.363590
2   image_003.jpg     malign          malign     0.314356     0.685644
3   image_004.jpg     benign          benign     0.508571     0.491429
4   image_005.jpg     benign          benign     0.907566     0.092434
..            ...        ...             ...          ...          ...
95  image_096.jpg     malign          malign     0.349210     0.650790
96  image_097.jpg     benign          benign     0.725956     0.274044
97  image_098.jpg     benign          benign     0.897110     0.102890
98  image_099.jpg     benign          benign     0.887086     0.112914
99  image_100.jpg     benign          benign     0.779876     0.220124

[100 rows x 5 columns]

## 1 - Quantas imagens são “benign” e “malign” em real_class?

In [5]:
benign_images = df["real_class"].value_counts()
benign_images

real_class
malign    55
benign    45
Name: count, dtype: int64

## 2 - Identifique em quais imagens o modelo errou a predição.

In [7]:
w_pred = (df["real_class"] != df["predicted_class"]).sum()
print(w_pred)

12

## 3 - Verifique se o modelo estava confiante mesmo quando errou.

In [8]:
w_pred = df[df["real_class"] != df["predicted_class"]]

In [9]:
w_pred

       image_path real_class predicted_class  prob_benign  prob_malign
20  image_021.jpg     malign          benign     0.807440     0.192560
26  image_027.jpg     malign          benign     0.818015     0.181985
27  image_028.jpg     malign          benign     0.860731     0.139269
41  image_042.jpg     benign          malign     0.251782     0.748218
46  image_047.jpg     malign          benign     0.609564     0.390436
65  image_066.jpg     malign          benign     0.835302     0.164698
67  image_068.jpg     benign          malign     0.186519     0.813481
69  image_070.jpg     malign          benign     0.590893     0.409107
70  image_071.jpg     malign          benign     0.677564     0.322436
76  image_077.jpg     malign          benign     0.690938     0.309062
80  image_081.jpg     benign          malign     0.341066     0.658934
91  image_092.jpg     malign          benign     0.897216     0.102784

In [11]:
w_malign = w_pred[w_pred["predicted_class"] == 'malign']
w_bening = w_pred[w_pred["predicted_class"] == 'benign']

prob_malign = w_malign['prob_malign']
prob_bening = w_bening['prob_benign']

probs_df = pd.concat([prob_malign, prob_bening])

mean_trust = probs_df.mean()

print(f"Confiança média do modelo ao errar foi: {mean_trust:.2f}")

Confiança média do modelo ao errar foi: 0.75

### 4 -Calcule:
a. TP (real malign, previsto malign)

b. TN (real benign, previsto benign)

c. FP (real benign, previsto malign)

d. FN (real malign, previsto benign)

In [33]:
df

       image_path real_class predicted_class  prob_benign  prob_malign
0   image_001.jpg     malign          malign     0.031429     0.968571
1   image_002.jpg     benign          benign     0.636410     0.363590
2   image_003.jpg     malign          malign     0.314356     0.685644
3   image_004.jpg     benign          benign     0.508571     0.491429
4   image_005.jpg     benign          benign     0.907566     0.092434
..            ...        ...             ...          ...          ...
95  image_096.jpg     malign          malign     0.349210     0.650790
96  image_097.jpg     benign          benign     0.725956     0.274044
97  image_098.jpg     benign          benign     0.897110     0.102890
98  image_099.jpg     benign          benign     0.887086     0.112914
99  image_100.jpg     benign          benign     0.779876     0.220124

[100 rows x 5 columns]

In [12]:
malign_df = df[df['real_class'] == 'malign']
benign_df = df[df['real_class'] == 'benign']

TP = (malign_df["real_class"] == malign_df['predicted_class']).sum()

TN = (benign_df["real_class"] == benign_df['predicted_class']).sum()

FP = (benign_df["real_class"] != benign_df['predicted_class']).sum()

FN = (malign_df["real_class"] != malign_df['predicted_class']).sum()

print(f"""
TP -> {TP}
TN -> {TN}
FP -> {FP}
FN -> {FN}
""")

TP -> 46
TN -> 42
FP -> 3
FN -> 9

### 5 - Calcule:
a. Acurácia: (TP+TN)/(TP+TN+FP+FN)

b. Precisão: TP/(TP+FP)

c. Recall: TP/(TP+FN)

d. Especificidade: TN/(TN+FP)

In [14]:
acc = (TP+TN)/(TP+TN+FP+FN)

prec = TP/(TP+FP)

recall = TP/(TP+FN)

espec = TN/(TN+FP)

print(f"""
Acurácia\t -> {acc:.2f}
Precisão\t -> {prec:.2f}
Recall\t\t -> {recall:.2f}
Especificidade\t -> {espec:.2f}
""")

Acurácia	 -> 0.88
Precisão	 -> 0.94
Recall		 -> 0.84
Especificidade	 -> 0.93

### 6 - Encontre as 5 imagens benign com menor prob_benign. O que isso pode indicar?

In [15]:
benign_df = df[df['real_class'] == 'benign'].sort_values(by='prob_benign')

lower_5_images = benign_df[:5]
lower_5_images

       image_path real_class predicted_class  prob_benign  prob_malign
67  image_068.jpg     benign          malign     0.186519     0.813481
41  image_042.jpg     benign          malign     0.251782     0.748218
80  image_081.jpg     benign          malign     0.341066     0.658934
47  image_048.jpg     benign          benign     0.502679     0.497321
3   image_004.jpg     benign          benign     0.508571     0.491429

Mostra indicios de que a probabilidade do modelo dar um falso negativo é grande, já que a probabilidade prevista de ser benigno é pequena

### 7 - Encontre as 5 imagens malign com maior prob_benign. O que isso pode indicar?

In [16]:
malign_df = df[df['real_class'] == 'malign'].sort_values(by='prob_benign', ascending=False)
malign_df
higher_5_images = malign_df[:5]
higher_5_images

       image_path real_class predicted_class  prob_benign  prob_malign
91  image_092.jpg     malign          benign     0.897216     0.102784
27  image_028.jpg     malign          benign     0.860731     0.139269
65  image_066.jpg     malign          benign     0.835302     0.164698
26  image_027.jpg     malign          benign     0.818015     0.181985
20  image_021.jpg     malign          benign     0.807440     0.192560

Mostra indicios de que a probabilidade de dar um falso positivo é grande, já que a probabilidade prevista de ser benigno é grande